/*
Wishlist Service

API for managing wishlists

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
)

// checks if the WishlistListWishlistsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishlistListWishlistsResponse{}

// WishlistListWishlistsResponse struct for WishlistListWishlistsResponse
type WishlistListWishlistsResponse struct {
	Wishlist             []WishlistWishlistResponse `json:"wishlist,omitempty"`
	NextPageToken        *string                    `json:"nextPageToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WishlistListWishlistsResponse WishlistListWishlistsResponse

// NewWishlistListWishlistsResponse instantiates a new WishlistListWishlistsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishlistListWishlistsResponse() *WishlistListWishlistsResponse {
	this := WishlistListWishlistsResponse{}
	return &this
}

// NewWishlistListWishlistsResponseWithDefaults instantiates a new WishlistListWishlistsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishlistListWishlistsResponseWithDefaults() *WishlistListWishlistsResponse {
	this := WishlistListWishlistsResponse{}
	return &this
}

// GetWishlist returns the Wishlist field value if set, zero value otherwise.
func (o *WishlistListWishlistsResponse) GetWishlist() []WishlistWishlistResponse {
	if o == nil || IsNil(o.Wishlist) {
		var ret []WishlistWishlistResponse
		return ret
	}
	return o.Wishlist
}

// GetWishlistOk returns a tuple with the Wishlist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistListWishlistsResponse) GetWishlistOk() ([]WishlistWishlistResponse, bool) {
	if o == nil || IsNil(o.Wishlist) {
		return nil, false
	}
	return o.Wishlist, true
}

// HasWishlist returns a boolean if a field has been set.
func (o *WishlistListWishlistsResponse) HasWishlist() bool {
	if o != nil && !IsNil(o.Wishlist) {
		return true
	}

	return false
}

// SetWishlist gets a reference to the given []WishlistWishlistResponse and assigns it to the Wishlist field.
func (o *WishlistListWishlistsResponse) SetWishlist(v []WishlistWishlistResponse) {
	o.Wishlist = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *WishlistListWishlistsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistListWishlistsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *WishlistListWishlistsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *WishlistListWishlistsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o WishlistListWishlistsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishlistListWishlistsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Wishlist) {
		toSerialize["wishlist"] = o.Wishlist
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WishlistListWishlistsResponse) UnmarshalJSON(data []byte) (err error) {
	varWishlistListWishlistsResponse := _WishlistListWishlistsResponse{}

	err = json.Unmarshal(data, &varWishlistListWishlistsResponse)

	if err != nil {
		return err
	}

	*o = WishlistListWishlistsResponse(varWishlistListWishlistsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "wishlist")
		delete(additionalProperties, "nextPageToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *WishlistListWishlistsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *WishlistListWishlistsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableWishlistListWishlistsResponse struct {
	value *WishlistListWishlistsResponse
	isSet bool
}

func (v NullableWishlistListWishlistsResponse) Get() *WishlistListWishlistsResponse {
	return v.value
}

func (v *NullableWishlistListWishlistsResponse) Set(val *WishlistListWishlistsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWishlistListWishlistsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWishlistListWishlistsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishlistListWishlistsResponse(val *WishlistListWishlistsResponse) *NullableWishlistListWishlistsResponse {
	return &NullableWishlistListWishlistsResponse{value: val, isSet: true}
}

func (v NullableWishlistListWishlistsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishlistListWishlistsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
