/*
wishlist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
)

// checks if the ListWishlistsRequestFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWishlistsRequestFilter{}

// ListWishlistsRequestFilter struct for ListWishlistsRequestFilter
type ListWishlistsRequestFilter struct {
	CustomerGrn *string `json:"customerGrn,omitempty"`
}

// NewListWishlistsRequestFilter instantiates a new ListWishlistsRequestFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWishlistsRequestFilter() *ListWishlistsRequestFilter {
	this := ListWishlistsRequestFilter{}
	return &this
}

// NewListWishlistsRequestFilterWithDefaults instantiates a new ListWishlistsRequestFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWishlistsRequestFilterWithDefaults() *ListWishlistsRequestFilter {
	this := ListWishlistsRequestFilter{}
	return &this
}

// GetCustomerGrn returns the CustomerGrn field value if set, zero value otherwise.
func (o *ListWishlistsRequestFilter) GetCustomerGrn() string {
	if o == nil || IsNil(o.CustomerGrn) {
		var ret string
		return ret
	}
	return *o.CustomerGrn
}

// GetCustomerGrnOk returns a tuple with the CustomerGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWishlistsRequestFilter) GetCustomerGrnOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerGrn) {
		return nil, false
	}
	return o.CustomerGrn, true
}

// HasCustomerGrn returns a boolean if a field has been set.
func (o *ListWishlistsRequestFilter) HasCustomerGrn() bool {
	if o != nil && !IsNil(o.CustomerGrn) {
		return true
	}

	return false
}

// SetCustomerGrn gets a reference to the given string and assigns it to the CustomerGrn field.
func (o *ListWishlistsRequestFilter) SetCustomerGrn(v string) {
	o.CustomerGrn = &v
}

func (o ListWishlistsRequestFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWishlistsRequestFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerGrn) {
		toSerialize["customerGrn"] = o.CustomerGrn
	}
	return toSerialize, nil
}

type NullableListWishlistsRequestFilter struct {
	value *ListWishlistsRequestFilter
	isSet bool
}

func (v NullableListWishlistsRequestFilter) Get() *ListWishlistsRequestFilter {
	return v.value
}

func (v *NullableListWishlistsRequestFilter) Set(val *ListWishlistsRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableListWishlistsRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableListWishlistsRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWishlistsRequestFilter(val *ListWishlistsRequestFilter) *NullableListWishlistsRequestFilter {
	return &NullableListWishlistsRequestFilter{value: val, isSet: true}
}

func (v NullableListWishlistsRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWishlistsRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


