/*
Wishlist Service

API for managing wishlists

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
)

// checks if the WishlistListWishlistItemsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishlistListWishlistItemsResponse{}

// WishlistListWishlistItemsResponse struct for WishlistListWishlistItemsResponse
type WishlistListWishlistItemsResponse struct {
	WishlistItems []WishlistWishlistItemResponse `json:"wishlistItems,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewWishlistListWishlistItemsResponse instantiates a new WishlistListWishlistItemsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishlistListWishlistItemsResponse() *WishlistListWishlistItemsResponse {
	this := WishlistListWishlistItemsResponse{}
	return &this
}

// NewWishlistListWishlistItemsResponseWithDefaults instantiates a new WishlistListWishlistItemsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishlistListWishlistItemsResponseWithDefaults() *WishlistListWishlistItemsResponse {
	this := WishlistListWishlistItemsResponse{}
	return &this
}

// GetWishlistItems returns the WishlistItems field value if set, zero value otherwise.
func (o *WishlistListWishlistItemsResponse) GetWishlistItems() []WishlistWishlistItemResponse {
	if o == nil || IsNil(o.WishlistItems) {
		var ret []WishlistWishlistItemResponse
		return ret
	}
	return o.WishlistItems
}

// GetWishlistItemsOk returns a tuple with the WishlistItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistListWishlistItemsResponse) GetWishlistItemsOk() ([]WishlistWishlistItemResponse, bool) {
	if o == nil || IsNil(o.WishlistItems) {
		return nil, false
	}
	return o.WishlistItems, true
}

// HasWishlistItems returns a boolean if a field has been set.
func (o *WishlistListWishlistItemsResponse) HasWishlistItems() bool {
	if o != nil && !IsNil(o.WishlistItems) {
		return true
	}

	return false
}

// SetWishlistItems gets a reference to the given []WishlistWishlistItemResponse and assigns it to the WishlistItems field.
func (o *WishlistListWishlistItemsResponse) SetWishlistItems(v []WishlistWishlistItemResponse) {
	o.WishlistItems = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *WishlistListWishlistItemsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistListWishlistItemsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *WishlistListWishlistItemsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *WishlistListWishlistItemsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o WishlistListWishlistItemsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishlistListWishlistItemsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WishlistItems) {
		toSerialize["wishlistItems"] = o.WishlistItems
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return toSerialize, nil
}

type NullableWishlistListWishlistItemsResponse struct {
	value *WishlistListWishlistItemsResponse
	isSet bool
}

func (v NullableWishlistListWishlistItemsResponse) Get() *WishlistListWishlistItemsResponse {
	return v.value
}

func (v *NullableWishlistListWishlistItemsResponse) Set(val *WishlistListWishlistItemsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWishlistListWishlistItemsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWishlistListWishlistItemsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishlistListWishlistItemsResponse(val *WishlistListWishlistItemsResponse) *NullableWishlistListWishlistItemsResponse {
	return &NullableWishlistListWishlistItemsResponse{value: val, isSet: true}
}

func (v NullableWishlistListWishlistItemsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishlistListWishlistItemsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


