/*
wishlist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
)

// checks if the WishlistAddItemToWishlistRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishlistAddItemToWishlistRequest{}

// WishlistAddItemToWishlistRequest struct for WishlistAddItemToWishlistRequest
type WishlistAddItemToWishlistRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	WishlistId *string `json:"wishlistId,omitempty"`
	ItemGrn *string `json:"itemGrn,omitempty"`
	PreferredQuantity *string `json:"preferredQuantity,omitempty"`
	Description *WishlistLocalizedText `json:"description,omitempty"`
	CustomerGrn *string `json:"customerGrn,omitempty"`
}

// NewWishlistAddItemToWishlistRequest instantiates a new WishlistAddItemToWishlistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishlistAddItemToWishlistRequest() *WishlistAddItemToWishlistRequest {
	this := WishlistAddItemToWishlistRequest{}
	return &this
}

// NewWishlistAddItemToWishlistRequestWithDefaults instantiates a new WishlistAddItemToWishlistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishlistAddItemToWishlistRequestWithDefaults() *WishlistAddItemToWishlistRequest {
	this := WishlistAddItemToWishlistRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *WishlistAddItemToWishlistRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistAddItemToWishlistRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *WishlistAddItemToWishlistRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *WishlistAddItemToWishlistRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetWishlistId returns the WishlistId field value if set, zero value otherwise.
func (o *WishlistAddItemToWishlistRequest) GetWishlistId() string {
	if o == nil || IsNil(o.WishlistId) {
		var ret string
		return ret
	}
	return *o.WishlistId
}

// GetWishlistIdOk returns a tuple with the WishlistId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistAddItemToWishlistRequest) GetWishlistIdOk() (*string, bool) {
	if o == nil || IsNil(o.WishlistId) {
		return nil, false
	}
	return o.WishlistId, true
}

// HasWishlistId returns a boolean if a field has been set.
func (o *WishlistAddItemToWishlistRequest) HasWishlistId() bool {
	if o != nil && !IsNil(o.WishlistId) {
		return true
	}

	return false
}

// SetWishlistId gets a reference to the given string and assigns it to the WishlistId field.
func (o *WishlistAddItemToWishlistRequest) SetWishlistId(v string) {
	o.WishlistId = &v
}

// GetItemGrn returns the ItemGrn field value if set, zero value otherwise.
func (o *WishlistAddItemToWishlistRequest) GetItemGrn() string {
	if o == nil || IsNil(o.ItemGrn) {
		var ret string
		return ret
	}
	return *o.ItemGrn
}

// GetItemGrnOk returns a tuple with the ItemGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistAddItemToWishlistRequest) GetItemGrnOk() (*string, bool) {
	if o == nil || IsNil(o.ItemGrn) {
		return nil, false
	}
	return o.ItemGrn, true
}

// HasItemGrn returns a boolean if a field has been set.
func (o *WishlistAddItemToWishlistRequest) HasItemGrn() bool {
	if o != nil && !IsNil(o.ItemGrn) {
		return true
	}

	return false
}

// SetItemGrn gets a reference to the given string and assigns it to the ItemGrn field.
func (o *WishlistAddItemToWishlistRequest) SetItemGrn(v string) {
	o.ItemGrn = &v
}

// GetPreferredQuantity returns the PreferredQuantity field value if set, zero value otherwise.
func (o *WishlistAddItemToWishlistRequest) GetPreferredQuantity() string {
	if o == nil || IsNil(o.PreferredQuantity) {
		var ret string
		return ret
	}
	return *o.PreferredQuantity
}

// GetPreferredQuantityOk returns a tuple with the PreferredQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistAddItemToWishlistRequest) GetPreferredQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.PreferredQuantity) {
		return nil, false
	}
	return o.PreferredQuantity, true
}

// HasPreferredQuantity returns a boolean if a field has been set.
func (o *WishlistAddItemToWishlistRequest) HasPreferredQuantity() bool {
	if o != nil && !IsNil(o.PreferredQuantity) {
		return true
	}

	return false
}

// SetPreferredQuantity gets a reference to the given string and assigns it to the PreferredQuantity field.
func (o *WishlistAddItemToWishlistRequest) SetPreferredQuantity(v string) {
	o.PreferredQuantity = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WishlistAddItemToWishlistRequest) GetDescription() WishlistLocalizedText {
	if o == nil || IsNil(o.Description) {
		var ret WishlistLocalizedText
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistAddItemToWishlistRequest) GetDescriptionOk() (*WishlistLocalizedText, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WishlistAddItemToWishlistRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given WishlistLocalizedText and assigns it to the Description field.
func (o *WishlistAddItemToWishlistRequest) SetDescription(v WishlistLocalizedText) {
	o.Description = &v
}

// GetCustomerGrn returns the CustomerGrn field value if set, zero value otherwise.
func (o *WishlistAddItemToWishlistRequest) GetCustomerGrn() string {
	if o == nil || IsNil(o.CustomerGrn) {
		var ret string
		return ret
	}
	return *o.CustomerGrn
}

// GetCustomerGrnOk returns a tuple with the CustomerGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistAddItemToWishlistRequest) GetCustomerGrnOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerGrn) {
		return nil, false
	}
	return o.CustomerGrn, true
}

// HasCustomerGrn returns a boolean if a field has been set.
func (o *WishlistAddItemToWishlistRequest) HasCustomerGrn() bool {
	if o != nil && !IsNil(o.CustomerGrn) {
		return true
	}

	return false
}

// SetCustomerGrn gets a reference to the given string and assigns it to the CustomerGrn field.
func (o *WishlistAddItemToWishlistRequest) SetCustomerGrn(v string) {
	o.CustomerGrn = &v
}

func (o WishlistAddItemToWishlistRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishlistAddItemToWishlistRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.WishlistId) {
		toSerialize["wishlistId"] = o.WishlistId
	}
	if !IsNil(o.ItemGrn) {
		toSerialize["itemGrn"] = o.ItemGrn
	}
	if !IsNil(o.PreferredQuantity) {
		toSerialize["preferredQuantity"] = o.PreferredQuantity
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CustomerGrn) {
		toSerialize["customerGrn"] = o.CustomerGrn
	}
	return toSerialize, nil
}

type NullableWishlistAddItemToWishlistRequest struct {
	value *WishlistAddItemToWishlistRequest
	isSet bool
}

func (v NullableWishlistAddItemToWishlistRequest) Get() *WishlistAddItemToWishlistRequest {
	return v.value
}

func (v *NullableWishlistAddItemToWishlistRequest) Set(val *WishlistAddItemToWishlistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWishlistAddItemToWishlistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWishlistAddItemToWishlistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishlistAddItemToWishlistRequest(val *WishlistAddItemToWishlistRequest) *NullableWishlistAddItemToWishlistRequest {
	return &NullableWishlistAddItemToWishlistRequest{value: val, isSet: true}
}

func (v NullableWishlistAddItemToWishlistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishlistAddItemToWishlistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


