/*
wishlist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
)

// checks if the WishlistUpdateWishlistRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishlistUpdateWishlistRequest{}

// WishlistUpdateWishlistRequest struct for WishlistUpdateWishlistRequest
type WishlistUpdateWishlistRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
	Payload *WishlistUpdateWishlistRequestPayload `json:"payload,omitempty"`
	PayloadMask []string `json:"payloadMask,omitempty"`
}

// NewWishlistUpdateWishlistRequest instantiates a new WishlistUpdateWishlistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishlistUpdateWishlistRequest() *WishlistUpdateWishlistRequest {
	this := WishlistUpdateWishlistRequest{}
	return &this
}

// NewWishlistUpdateWishlistRequestWithDefaults instantiates a new WishlistUpdateWishlistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishlistUpdateWishlistRequestWithDefaults() *WishlistUpdateWishlistRequest {
	this := WishlistUpdateWishlistRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *WishlistUpdateWishlistRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistUpdateWishlistRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *WishlistUpdateWishlistRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *WishlistUpdateWishlistRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WishlistUpdateWishlistRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistUpdateWishlistRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WishlistUpdateWishlistRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WishlistUpdateWishlistRequest) SetId(v string) {
	o.Id = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *WishlistUpdateWishlistRequest) GetPayload() WishlistUpdateWishlistRequestPayload {
	if o == nil || IsNil(o.Payload) {
		var ret WishlistUpdateWishlistRequestPayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistUpdateWishlistRequest) GetPayloadOk() (*WishlistUpdateWishlistRequestPayload, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *WishlistUpdateWishlistRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given WishlistUpdateWishlistRequestPayload and assigns it to the Payload field.
func (o *WishlistUpdateWishlistRequest) SetPayload(v WishlistUpdateWishlistRequestPayload) {
	o.Payload = &v
}

// GetPayloadMask returns the PayloadMask field value if set, zero value otherwise.
func (o *WishlistUpdateWishlistRequest) GetPayloadMask() []string {
	if o == nil || IsNil(o.PayloadMask) {
		var ret []string
		return ret
	}
	return o.PayloadMask
}

// GetPayloadMaskOk returns a tuple with the PayloadMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistUpdateWishlistRequest) GetPayloadMaskOk() ([]string, bool) {
	if o == nil || IsNil(o.PayloadMask) {
		return nil, false
	}
	return o.PayloadMask, true
}

// HasPayloadMask returns a boolean if a field has been set.
func (o *WishlistUpdateWishlistRequest) HasPayloadMask() bool {
	if o != nil && !IsNil(o.PayloadMask) {
		return true
	}

	return false
}

// SetPayloadMask gets a reference to the given []string and assigns it to the PayloadMask field.
func (o *WishlistUpdateWishlistRequest) SetPayloadMask(v []string) {
	o.PayloadMask = v
}

func (o WishlistUpdateWishlistRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishlistUpdateWishlistRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.PayloadMask) {
		toSerialize["payloadMask"] = o.PayloadMask
	}
	return toSerialize, nil
}

type NullableWishlistUpdateWishlistRequest struct {
	value *WishlistUpdateWishlistRequest
	isSet bool
}

func (v NullableWishlistUpdateWishlistRequest) Get() *WishlistUpdateWishlistRequest {
	return v.value
}

func (v *NullableWishlistUpdateWishlistRequest) Set(val *WishlistUpdateWishlistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWishlistUpdateWishlistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWishlistUpdateWishlistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishlistUpdateWishlistRequest(val *WishlistUpdateWishlistRequest) *NullableWishlistUpdateWishlistRequest {
	return &NullableWishlistUpdateWishlistRequest{value: val, isSet: true}
}

func (v NullableWishlistUpdateWishlistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishlistUpdateWishlistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


