/*
wishlist/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
)

// checks if the WishlistBulkCreateSharingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishlistBulkCreateSharingRequest{}

// WishlistBulkCreateSharingRequest struct for WishlistBulkCreateSharingRequest
type WishlistBulkCreateSharingRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	SharingRequests []WishlistSharingRequest `json:"sharingRequests,omitempty"`
}

// NewWishlistBulkCreateSharingRequest instantiates a new WishlistBulkCreateSharingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishlistBulkCreateSharingRequest() *WishlistBulkCreateSharingRequest {
	this := WishlistBulkCreateSharingRequest{}
	return &this
}

// NewWishlistBulkCreateSharingRequestWithDefaults instantiates a new WishlistBulkCreateSharingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishlistBulkCreateSharingRequestWithDefaults() *WishlistBulkCreateSharingRequest {
	this := WishlistBulkCreateSharingRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *WishlistBulkCreateSharingRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistBulkCreateSharingRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *WishlistBulkCreateSharingRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *WishlistBulkCreateSharingRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSharingRequests returns the SharingRequests field value if set, zero value otherwise.
func (o *WishlistBulkCreateSharingRequest) GetSharingRequests() []WishlistSharingRequest {
	if o == nil || IsNil(o.SharingRequests) {
		var ret []WishlistSharingRequest
		return ret
	}
	return o.SharingRequests
}

// GetSharingRequestsOk returns a tuple with the SharingRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WishlistBulkCreateSharingRequest) GetSharingRequestsOk() ([]WishlistSharingRequest, bool) {
	if o == nil || IsNil(o.SharingRequests) {
		return nil, false
	}
	return o.SharingRequests, true
}

// HasSharingRequests returns a boolean if a field has been set.
func (o *WishlistBulkCreateSharingRequest) HasSharingRequests() bool {
	if o != nil && !IsNil(o.SharingRequests) {
		return true
	}

	return false
}

// SetSharingRequests gets a reference to the given []WishlistSharingRequest and assigns it to the SharingRequests field.
func (o *WishlistBulkCreateSharingRequest) SetSharingRequests(v []WishlistSharingRequest) {
	o.SharingRequests = v
}

func (o WishlistBulkCreateSharingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishlistBulkCreateSharingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.SharingRequests) {
		toSerialize["sharingRequests"] = o.SharingRequests
	}
	return toSerialize, nil
}

type NullableWishlistBulkCreateSharingRequest struct {
	value *WishlistBulkCreateSharingRequest
	isSet bool
}

func (v NullableWishlistBulkCreateSharingRequest) Get() *WishlistBulkCreateSharingRequest {
	return v.value
}

func (v *NullableWishlistBulkCreateSharingRequest) Set(val *WishlistBulkCreateSharingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWishlistBulkCreateSharingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWishlistBulkCreateSharingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishlistBulkCreateSharingRequest(val *WishlistBulkCreateSharingRequest) *NullableWishlistBulkCreateSharingRequest {
	return &NullableWishlistBulkCreateSharingRequest{value: val, isSet: true}
}

func (v NullableWishlistBulkCreateSharingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishlistBulkCreateSharingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


