/*
Wishlist Service

API for managing wishlists

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wishlist

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WishlistGetItemFromWishlistRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishlistGetItemFromWishlistRequest{}

// WishlistGetItemFromWishlistRequest struct for WishlistGetItemFromWishlistRequest
type WishlistGetItemFromWishlistRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
}

type _WishlistGetItemFromWishlistRequest WishlistGetItemFromWishlistRequest

// NewWishlistGetItemFromWishlistRequest instantiates a new WishlistGetItemFromWishlistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishlistGetItemFromWishlistRequest(tenantId string, id string) *WishlistGetItemFromWishlistRequest {
	this := WishlistGetItemFromWishlistRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewWishlistGetItemFromWishlistRequestWithDefaults instantiates a new WishlistGetItemFromWishlistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishlistGetItemFromWishlistRequestWithDefaults() *WishlistGetItemFromWishlistRequest {
	this := WishlistGetItemFromWishlistRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *WishlistGetItemFromWishlistRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *WishlistGetItemFromWishlistRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *WishlistGetItemFromWishlistRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *WishlistGetItemFromWishlistRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WishlistGetItemFromWishlistRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WishlistGetItemFromWishlistRequest) SetId(v string) {
	o.Id = v
}

func (o WishlistGetItemFromWishlistRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishlistGetItemFromWishlistRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *WishlistGetItemFromWishlistRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWishlistGetItemFromWishlistRequest := _WishlistGetItemFromWishlistRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWishlistGetItemFromWishlistRequest)

	if err != nil {
		return err
	}

	*o = WishlistGetItemFromWishlistRequest(varWishlistGetItemFromWishlistRequest)

	return err
}

type NullableWishlistGetItemFromWishlistRequest struct {
	value *WishlistGetItemFromWishlistRequest
	isSet bool
}

func (v NullableWishlistGetItemFromWishlistRequest) Get() *WishlistGetItemFromWishlistRequest {
	return v.value
}

func (v *NullableWishlistGetItemFromWishlistRequest) Set(val *WishlistGetItemFromWishlistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWishlistGetItemFromWishlistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWishlistGetItemFromWishlistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishlistGetItemFromWishlistRequest(val *WishlistGetItemFromWishlistRequest) *NullableWishlistGetItemFromWishlistRequest {
	return &NullableWishlistGetItemFromWishlistRequest{value: val, isSet: true}
}

func (v NullableWishlistGetItemFromWishlistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishlistGetItemFromWishlistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


